### ISSUE TITLE
Add number rules

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/stylelint-config-wikimedia#1]
```
"number-leading-zero": [ "always" ],
"number-no-trailing-zeros": true,
"number-zero-length-no-unit": true,
```

**Comment by edg2s** [comment]
I'm not confident that CSS units will always contain a dimensionless constant value of zero, for example imagine .freezing { temperature-less-than: 0celsius; }.

Also consider a case where multiple zeros refer to different dimensions, e.g. translate: 0px 0px 0deg.

That said this can be considered tech debt.
