### ISSUE TITLE
Add `box-sizing`, `box-shadow`, `hyphens`, `transform` & `transition` to 'property-blacklist' rule as long as corresponding mixins are there

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#103]
We feature a number of property mixins for needed cross-browser support. We should enforce their usage in our deployed products as long as they are part of mediawiki.mixins and reflect our browser support matrix by adding them on ['property-blacklist'](https://stylelint.io/user-guide/rules/property-blacklist) rule.
The only way to get such property in is to then use the corresponding mixin.

Unluckily we can't rely on some more automated magic like Autoprefixer in our environments.
Proposal would mean a bit more manual work, but ensuring we're living up to our browser support matrix promise.

**Comment by Krinkle** [comment]
Sounds good to me.

**Comment by edg2s** [comment]
Most of these mixins have been removed now.

**Comment by Volker-E** [comment]
Yeah, it doesn't seem reasonable any more (luckily).
