### ISSUE TITLE
Whole Less mixin whitespace area untouched

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#11]
Whole Less mixin notation stays with current rules yet untouched, for example:
`.oo-ui-inline-spacing(0.5em);`

**Comment by edg2s** [comment]
Sounds like an upstream bug. Stylelint support for LESS is considered "experimental".

**Comment by jdforrester** [comment]
Sort-of related to stylelint/stylelint#1342 maybe?

**Comment by jdforrester** [comment]
Looks like this was fixed by stylelint release 6.6.0 ("[Fixed: selector-targeting rules ignore Less mixins and extends.](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#660)").
