### ISSUE TITLE
minimist vulnerability needs update to ^1.2.3

### ISSUE THREAD

**Issue by djstreat** [wikimedia/stylelint-config-wikimedia#115]
It looks like this package is dependent on a [vulnerable version of minimist](https://www.npmjs.com/advisories/1179), and might need to be updated past 1.2.3.

**Comment by jdforrester** [comment]
Yup. We're waiting on multiple downstream updates, sadly (mkdirp -> eslint and gonzales-pe -> postcss-sass -> stylelint)

**Comment by legoktm** [comment]
mkdirp/eslint are fixed now, but gonzales-pe seems stalled... https://github.com/tonyganch/gonzales-pe/pull/304 :(

**Comment by jdforrester** [comment]
Yeah. :-(

**Comment by legoktm** [comment]
Now that gonzales-pe is fixed, I ran `npm audit` against this library and another repo that depended upon this one and it didn't find any vulnerable dependencies. Is there anything left that we need to do?

**Comment by jdforrester** [comment]
> Now that gonzales-pe is fixed, I ran `npm audit` against this library and another repo that depended upon this one and it didn't find any vulnerable dependencies. Is there anything left that we need to do?

Sorry, yes, this was fixed by release `v0.10.0`.
