### ISSUE TITLE
Add `stylelint-value-border-zero` plugin to package

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#12]
[`stylelint-value-border-zero` stylelint plugin](https://www.npmjs.com/package/stylelint-value-border-zero) is a good addition to our central ruleset as there's no reason for mixing the border-shorthand reset `none` and `0` and latter is shorter (ah!) and aligns with `margin` and `padding`. 
`border: 0;` for the win!

**Comment by edg2s** [comment]
What about outline?

**Comment by edg2s** [comment]
... and box-shadow ...

**Comment by jdforrester** [comment]
@edg2s – Filed as #21 and #22.
