### ISSUE TITLE
Disallow @import rules except for LESS

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/stylelint-config-wikimedia#134]
Using `@import` in production CSS code should be forbidden by a stylerule. Doing this is basically never intentional as it would mean that the browser blocks all rendering while it parses the stylesheet until it has lazily discovered, downloaded, and parsed this other CSS file first.

Also, given that the CSS syntax requires `@import` to be at the top of a stylesheet, these statements generally stop working after bundling anyway. To bundle CSS files, one should use an RL module bundle definition with multiple style files, or use LESS to import them.

Which brings us to an interesting edg case: Using `@import` in a LESS file can still cause the same issue if the subject of the import is a `.css` file since the LESS specification says to only include/resolve other LESS files, unless the `@import (inline)` instruction is used. The number of times we've done this intentionally and purposefully is exactly zero. The only time I've seen it at all was in [change 682085](https://gerrit.wikimedia.org/r/c/mediawiki/core/+/682085/) after the above mistake was made as a temporary fix, which could still work even with this rule in place through an inline disable comment.

As such, I'm proposing that we error by default for all `@import` statements in CSS files, and any `@import` statemess for `.css` files in a LESS file – regardless of whether it has `(inline)` specified. If at some point in the next ten years there is another instance of this being done temporarily/intentionally, one can always disable the rule locally on that line, which seems worth the price for all other cases where you'd likely need to be reminded about it via a stylelint rule if you did it by accident or didn't know why it matters.

**Comment by Volker-E** [comment]
@Krinkle With [stylelint v14 onwards](https://github.com/wikimedia/stylelint-config-wikimedia/pull/147), that's very simple (just waiting for somebody to merge):
```js
	"rules": {
		"at-rule-disallowed-list": "import"
	},
	"overrides": [ {
		"files": [ "**/*.less" ],
		"customSyntax": "postcss-less",
		"rules": {
			// Disallow @import rules except for LESS, see #134.
			"at-rule-disallowed-list": null
		}
	} ]
```

**Comment by Krinkle** [comment]
@Volker-E Can you confirm that this will only allow `@import`ing "of" a LESS file, rather than allowing all `@import` "in" a LESS file? What matters for this issue is that we disallow importing of CSS files. Whether the line of code is inside a LESS or CSS file doesn't matter. It is problem inside a LESS file as well, because `@import "foo.css"` would remain unchanged by the Less processor and cause the same problem.

**Comment by edg2s** [comment]
The above patch would only disallow imports **in** CSS files.

**Comment by edg2s** [comment]
I don't think there is an existing rule that would allow you to block imports of a specific file type.

**Comment by edg2s** [comment]
This second commit https://github.com/wikimedia/stylelint-config-wikimedia/commit/3559278862ff990e86ff7e4e09b202b1a1dbdef9 adds a custom rule that disallows any imports not handled by LESS.
