### ISSUE TITLE
Add browser support rules

### ISSUE THREAD

**Issue by edg2s** [wikimedia/stylelint-config-wikimedia#14]
In theory we should be able to add "no-browser-hacks" for Grade C+ browsers and "no-unsupported-browser-features" for Grade A browsers. The latter will probably throw a bunch of warnings because we regularly use features that aren't supported in IE9 (mostly transitions).

**Comment by jdforrester** [comment]
I think this is reasonable. Patch forthcoming.

**Comment by edg2s** [comment]
Resolved by #125
