### ISSUE TITLE
Support @counter-style and related properties

### ISSUE THREAD

**Issue by amire80** [wikimedia/stylelint-config-wikimedia#145]
Both Firefox and Chrome now support the @counter-style feature, which is described at https://www.w3.org/TR/css-counter-styles-3/

stylelint doesn't seem to support it yet, and fails with property-no-unknown.

The necessary properties are:
* system
* negative
* prefix
* suffix
* range
* pad
* fallback
* symbols
* additive-symbols
* speak-as

Many code examples can be found at https://www.w3.org/TR/predefined-counter-styles/ . They were checked by W3C and are supposed to be valid.

This feature is used on Wikipedia in some languages, such as Santali (sat.wikipedia.org) and Meetei (mni.wikipedia.org), and Wikimedia's code is checked using stylelint, so it would be nice to support it properly without stylelint-disable.

**Comment by amire80** [comment]
Upstream: https://github.com/stylelint/stylelint/issues/5385

**Comment by Volker-E** [comment]
Fixed by #147
