### ISSUE TITLE
Consider making postcss-less a dependency

### ISSUE THREAD

**Issue by edg2s** [wikimedia/stylelint-config-wikimedia#153]
In Stylelint 14 this has to be installed manually, which we didn't have to do in the past.

**Comment by Volker-E** [comment]
Agreed, and also 'postcss-scss' for WMDE and others.

**Comment by edg2s** [comment]
SCSS seems like more of an edge case. LESS is supported by ResourceLoader.

**Comment by Volker-E** [comment]
An edge case in preference by second-biggest chapter?
Also stylelint-config-wikimedia shouldn't be RL/MW exclusive from my understanding.
https://trends.google.com/trends/explore?q=scss,%2Fm%2F0gjd0jv
https://trends.google.com/trends/explore?q=%2Fm%2F054k6n_,%2Fm%2F0gjd0jv

**Comment by edg2s** [comment]
> An edge case in preference by second-biggest chapter?
SCSS is a handful of repos out of hundreds for our actual users. If we're adding a dependency there should be a lot more than 1% of repos actually using it (which is definitely the case with LESS).

> Also stylelint-config-wikimedia shouldn't be RL/MW exclusive from my understanding.
Yes - this is stylelint-config-wikimedia not stylelint-config-mediawiki, but we don't have a mediawiki ruleset (yet) and in practice 99% of our users are mediawiki.

**Comment by edg2s** [comment]
Moved to #155
