### ISSUE TITLE
Add `outline` to ignored no-unsupported-browser-features

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#166]
`outline` might have had some support issues in the past in various browsers, a.o. not following border-radius property.
But the general feedback of 'no-unsupported-browser-features' plugin 
> Unexpected browser feature   plugin/no-unsupported-browser-features
>            "outline" is only partially                                        
>            supported by IE 11, Edge                                           
>            12,13,14 

does seem overly strict to me. 

**Proposal**
Therefore proposing to add an ignore rule to plugin.

**Comment by edg2s** [comment]
This can probably be closed per https://github.com/wikimedia/stylelint-config-wikimedia/pull/167#issuecomment-1106895826
