### ISSUE TITLE
Allow CSS3 selectors?

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/stylelint-config-wikimedia#196]
https://caniuse.com/css-sel3

These should be fine now, I suppose?

**Comment by edg2s** [comment]
Where do we not allow them?

**Comment by Volker-E** [comment]
That's the context https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Cite/+/844069/1/modules/ext.cite.style.css

**Comment by edg2s** [comment]
We use `:after` everywhere, don't know what that is failing in Cite, but it shouldn't be.
