### ISSUE TITLE
Replace single colon with double colon notation for pseudo elements

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#200]
We've followed [single colon](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements?retiredLocale=de#browser_compatibility) `:` notation for pseudo elements to provide support for IE 6-8. 

### Proposal
It's time to follow CSS standard and expect double `::` as notation.

**Comment by Volker-E** [comment]
Open question if we should update test cases
```
.t:HOVER:unknown:not(.a)::BEFORE::pseudo {
```

**Comment by jdforrester** [comment]
> Seems like a meh kind of change, `:` is like to be supported forever and having to remember how many colons to use is harder than just always using 1. Presumably the rule autofixes?

Yes: https://stylelint.io/user-guide/rules/selector-pseudo-element-colon-notation/
