### ISSUE TITLE
Updating to Stylelint 15 as dependency and stylelint-config-wikimedia releases

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#202]
### Summary
Stylelint has released v15.n recently. See the [migration guide](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-15.md).

### Rollout proposal
I'd propose we 

- [x] #206
- [ ] then update to Stylelint v15, upgrade other build dependencies and introduce Node 18 support and make 0.15.0 release.

**Comment by Volker-E** [comment]
Most excitingly [is addition of](https://github.com/stylelint/stylelint/pull/6511) `declaration-property-value-no-unknown`

**Comment by edg2s** [comment]
Is that compatible with LESS?
