### ISSUE TITLE
Disallow use of classes prefixed with `page-`

### ISSUE THREAD

**Issue by jdlrobson** [wikimedia/stylelint-config-wikimedia#212]
I'm not sure if it's possible to do this in stylelint but we should error when we encounter a class pattern that is prefixed with ".page-" (unless it is `body.page-`)

Context: In https://phabricator.wikimedia.org/T337741 we discovered several classes "page-list", "page-actions-menu" which are applying to the body tag on certain pages with certain titles.

This went almost a decade unnoticed, so was not obvious, so I think a stylelint discouragement would help here.

**Comment by MatmaRex** [comment]
I think it's already disallowed here? https://github.com/wikimedia/stylelint-config-wikimedia/blob/a6e9d67d36bcf7343d9c7d3157690849729c9962/mediawiki.js#L10
