### ISSUE TITLE
The `stylelint-stylistic` package has been deprecated

### ISSUE THREAD

**Issue by AnYiEE** [wikimedia/stylelint-config-wikimedia#225]
The [stylelint 16.0](https://github.com/stylelint/stylelint/releases) has been released, and [stylelint-stylistic](https://www.npmjs.com/package/stylelint-stylistic) used by stylelint-config-wikimedia is not compatible with it and has been marked as deprecated. Please switch to [@stylistic/stylelint-plugin](https://github.com/stylelint-stylistic/stylelint-stylistic). Thank you all. @edg2s @jdforrester

**Comment by jdforrester** [comment]
This should now be resolved, with release v0.17.0.
