### ISSUE TITLE
Incompatible with grunt-stylelint 0.20.0: ruleName not exposed

### ISSUE THREAD

**Issue by Nikerabbit** [wikimedia/stylelint-config-wikimedia#231]
> Error: stylelint requires plugins to expose a ruleName. The plugin "/home/runner/work/mediawiki-extensions-Nimiarkisto/mediawiki-extensions-Nimiarkisto/node_modules/stylelint-config-wikimedia/node_modules/stylelint-stylistic/dist/main.js" is not doing this, so will not work with stylelint. Please file an issue with the plugin.

**Comment by jdforrester** [comment]
That's probably just fall-out from #225. We're not compatible with Stylelint 16 yet, but #229 should fix that. (`@stylistic` is an upstream plug-in; we're just a ruleset.)

**Comment by jdforrester** [comment]
This should now be resolved, with release v0.17.0.
