### ISSUE TITLE
Review all the rest of the stylelint rules to see if we should add them

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/stylelint-config-wikimedia#3]

**Comment by Volker-E** [comment]
We should add/not add (as of stylelint v7.3.1):

- `color-no-invalid-hex` **Yes**. Disallow 2 or 5 hex char values.
- `function-blacklist` **No**. No current use case.
- `function-linear-gradient-no-nonstandard-direction` **Yes**. Ensure only standard-syntax in code. 
- `function-max-empty-lines` **Yes**. No extra lines in multiline property values like `transform`. Don't know if breaking lines isn't prohibited by other rules already, but let's make sure.
- `function-name-case: [ "lower " ]` **Yes**. No need for `cAlc()`
- `function-whitelist`: **No**. No current use case.
- `number-max-precision`: **Unclear**. `3` seems to be a good value especially given our `em` sub-pixel rendering counter-actions, but might be overkill
- `time-no-imperceptible`: **Yes**. No reason not to support this. See also https://phabricator.wikimedia.org/T77949
- `unit-blacklist`: **Maybe**. Could make sense, currently it seems like overkill.
- `unit-case: [ "lower " ]`: **Yes**. No reason to have `10PX` somewhere.
- `unit-no-unknown`: Yes, definitely.
- `unit-no-unknown`: **No**.
- `value-keyword-case: [ "lower " ]`: **Yes**. No reason to have `display: bLOck` somewhere.
- `value-no-vendor-prefix`: **No**, not currently. Might be interesting in the future, or in projects with f.e. Autoprefixer
- `value-list-max-empty-lines`: **Yes**. `0`
- `custom-property-empty-line-before`/`custom-property-pattern` **No**. Makes no sense.
- `property-case: [ "lower " ]`: **Yes**. No reason to have `dISplaY: block` somewhere.
- `property-no-unknown`: **Yes**
- `property-no-vendor-prefix`: **No**, not currently. Might be interesting in the future, or in projects with f.e. Autoprefixer
- `keyframe-declaration-no-important`: **No**. No need.
- `declaration-block-no-shorthand-property-overrides`: **Yes**

That's the analysis till [“Block” in the stylelint rules documentation](http://stylelint.io/user-guide/rules/).

**Comment by jdforrester** [comment]
These sound good to me, except for `unit-no-unknown` where you say both "Yes, definitely." and "No." immediately thereafter. :-) Did you mean for `unit-whitelist` instead?

**Comment by Volker-E** [comment]
@jdforrester Haha, nice one. You're right, I meant `unit-whitelist`. Updated the comment.
Also extended the comment with the rest of the available rules.

**Comment by Volker-E** [comment]
I've prepared a PR. 
After looking into the additions, it might be even more clear for us and for external developers, to add rules that we don't want to have included as well:

`"at-rule-name-newline-after": null`

Otherwise we're repeatedly having to deal with the lookup game.

**Comment by ntwb** [comment]
> Otherwise we're repeatedly having to deal with the lookup game.

There's a neat ESLint plugin, [eslint-find-rules](https://github.com/sarbbottam/eslint-find-rules), I'd be cool see a stylelint version of this 😏

**Comment by Volker-E** [comment]
Nice one, @ntwb!

**Comment by jdforrester** [comment]
@ntwb Is there an Issue for that? Should there be, to encourage people who might want to help out?

**Comment by ntwb** [comment]
There is now @jdforrester, or I've proposed that we should have a wish list for such ideas 😄

**Comment by ntwb** [comment]
Done, nothing fancy, but added a section on the wiki home page 👍

https://github.com/stylelint/stylelint/wiki

**Comment by Volker-E** [comment]
@edg2s To proceed with the comments on the merged pull request:
- `shorthand-property-no-redundant-values` – I really think that it's acceptable for developers who write CSS to read the spec. :P I also wouldn't want to change the property again, as it's too small of a problem.
- `function-url-scheme-whitelist` – don't understand what went wrong here, the rule is `"function-url-scheme-whitelist": ["https", "data"]` so data URIs should work. Do you have an example for me?
- `selector-attribute-brackets-space-inside` – should be a follow-up pull request IMHO
- error messages with `DXImageTransform.Microsoft.*` is fixed in https://github.com/wikimedia/stylelint-config-wikimedia/pull/40

**Comment by ntwb** [comment]
To add a note, there are deprecated rules in the current config See https://github.com/wikimedia/grunt-stylelint/issues/32

(I suspect there will be more than just that one rule mentioned there)

**Comment by Volker-E** [comment]
We should consider adding 
- `selector-max-specificity` (since 4.5.0) and
- `font-family-no-missing-generic-family-keyword` (currently only in HEAD, not released yet)

Projects won't probably not be too happy, but for future sanity we should consider `selector-max-specificity` with a sensible default.

**Comment by Volker-E** [comment]
When #77 is in, this should ready to be closed.

**Comment by Volker-E** [comment]
We're using stylelint v9.6.0 in v0.5.0. Since then up until latest v9.9.0 there has been no additional rules added, we've got everything useful covered now. Hence closing as resolved.
