### ISSUE TITLE
"font-family-name-quotes" rule – "always-where-recommended" preferable

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#33]
Quotes on `font-family` property are one of those fuzzy things in CSS. It is [_very uncommon_](https://drafts.csswg.org/css-fonts-3/#font-family-prop) to quote all custom font family names in CSS, therefore I'd suggest to use **`always-where-recommended`** instead of `always-unless-keyword`

Error with `always-unless-keyword`, ok with `always-where-recommended`
`font-family: "Linux Libertine", "Hoefler Text", Georgia, "Times New Roman", Times, serif;`

Enforced with `always-unless-keyword`:
`font-family: "Linux Libertine", "Hoefler Text", "Georgia", "Times New Roman", "Times", serif;`

Enforced with `always-where-required` (_updated_):
`font-family: Linux Libertine, Hoefler Text, Georgia, Times New Roman, Times, serif;`

Moreover the quotes aren't even necessary as long as font family name is “a sequence of one or more identifiers” as laid out by Mathias Bynens in this [insightful article](https://mathiasbynens.be/notes/unquoted-font-family).

Comparing implementation of other projects.

- [W3C CSS Fonts Module Level 3](https://drafts.csswg.org/css-fonts-3/#font-family-prop):<br>
`font-family: "New Century Schoolbook", serif`
- [WordPress 4.6:](https://core.svn.wordpress.org/trunk/wp-includes/css/admin-bar.css#l44)<br>
`font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;`
- [Drupal 8, theme Bartik](http://cgit.drupalcode.org/drupal/tree/core/themes/bartik/css/base/elements.css?h=8.1.7#n13) (comes with default installation):<br>
`font-family: Georgia, "Times New Roman", Times, serif;`

**Comment by edg2s** [comment]
The problem with -unless-recommended is it is somewhat arbitrary part of the spec - it has no relation to a specific category of fonts, or a technical escaping requirement.

I would recommend either the -unless-keyword, which at least has the benefit of making it visually clear which rules are font names and which are keywords, or -unless-required - which consistently leaves out quotes unless they are required by the spec (e.g. contain a hyphen).

**Comment by jdlrobson** [comment]
I propose only using quotes when required. e.g. font-family: Georgia, "Times New Roman"

**Comment by trevorparscal** [comment]
I personally like the look of always-unless-keyword, but I recognize it may be overly restrictive. I think always-unless-keyword it could help make it clear what is a keyword an what is a font family name.

**Comment by Volker-E** [comment]
Besides proprietary CSS extensions, there are just five different generic `font-family` values, which –opinion(!)– every somewhat experienced CSS author knows about (at least the last three, because first two are not of good use): 
  - cursive
  - fantasy
  - monospace
  - sans-serif
  - serif

**Comment by Krinkle** [comment]
+1 for `always-unless-keyword`. I think it's more predictable, looks more consistent to the eye, and allows for smoother reading and reviewing of code. 

Remember that this is for our authored format. If we want to save a few bits by omitting quotes in the compressed format, that's orthogonal to this.

**Comment by Volker-E** [comment]
I should be more careful with my examples to make a point. Duh. 
The example with **`always-where-required`**:
`font-family: Linux Libertine, Hoefler Text, Georgia, Times New Roman, Times, serif;`

**Comment by edg2s** [comment]
So to clarify the three options with examples that illustrate the differences

**`where-required`**
`font-family: "Oxygen-Sans", "Hawaii 5-0", Georgia, Arial Black, Linux Libertine, serif;`

**`where-recommended`**
`font-family: "Oxygen-Sans", "Hawaii 5-0", Georgia, "Arial Black", "Linux Libertine", serif;`

**`unless-keyword`**
`font-family: "Oxygen-Sans", "Hawaii 5-0", "Georgia", "Arial Black", "Linux Libertine", serif;`

The current setting is `unless-keyword` and has 3 in favour. Volker is proposing `where-recommended`.

**Comment by edg2s** [comment]
@jdlrobson you said to use "when required" but the example you gave was "when recommended"...

**Comment by edg2s** [comment]
Also many editors will colour strings differently.
SublimeText:
![image](https://cloud.githubusercontent.com/assets/180672/17568928/cc43a202-5efa-11e6-9fbf-84b5bead6fbb.png)
Ace:
![image](https://cloud.githubusercontent.com/assets/180672/17568980/14af5f0e-5efb-11e6-94e3-7a8866dedbe4.png)

**Comment by jdittrich** [comment]
+1 for *always unless keyword.*

**Comment by Volker-E** [comment]
The majority here has a pretty clear winner with `always-unless-keyword`. Nearly twenty years of working with [CSS' `font`](https://www.w3.org/TR/CSS1/#font) hasn't made my argumentation strong enough to avoid looking at something superfluous and feelingly wrong on a daily base. ;)
