### ISSUE TITLE
Remove `string-quotes` rule for now

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#4]
`"string-quotes": [ "single" ]` should be discussed more broadly before setting it centralized – there's no guideline of it at https://www.mediawiki.org/wiki/Manual:Coding_conventions/CSS yet.

**Comment by jdforrester** [comment]
I'm pretty opposed to this. Standardising on this is basic, and we use single quotes throughout Wikimedia coding conventions in JS, PHP etc.

**Comment by edg2s** [comment]
I can't see why enforcing single quotes would be problematic or controversial.

**Comment by Volker-E** [comment]
If you look at https://www.mediawiki.org/wiki/Manual:Coding_conventions/PHP there's no clear picture on the string-quotes. Mixing `'` and `"` throughout the page. Also writing `[type='text']` feels utterly wrong coming from HTML and quoting – out of historic-context – attributes consistently with `"`.

**Comment by edg2s** [comment]
We can't enforce quotes in PHP because '$foo' is different to "$foo", but in core it is most common to use single quotes unless variables are used.

With HTML attributes, one could make the same argument about JS though, e.g input.type = 'text';

While the attribute selector looks like an attribute assignment it's probably a good thing to remember that '=' has a completely different meaning: equivalence, not assignment.

**Comment by Volker-E** [comment]
I'm coming from the HTML side, we've just recently had a [conversation on wikitech-l](https://lists.wikimedia.org/pipermail/wikitech-l/2016-May/085463.html), where @brion stated:
> *Quote attributes consistently and predictably.*
* Always use double-quotes on attributes in output.

Or a discussion I had some point earlier on with @Krinkle where he was arguing for double quotes on CSS attribute selectors as well in contrast to me, when I wanted to get rid of the quotes on those as synthetical sugar anyways. As WMF currently doesn't have clear stated HTML coding conventions, attribute selector quotes should still orientate on the HTML way of writing things and the most common case is a double quote.

**Comment by edg2s** [comment]
I see no reason to align with HTML strings over say JS. HTML strings are one way of generating DOM as in the JS API. In the JS API we using single quotes: input = document.createNode('input'); input.type = 'text'.

Furthermore attributes selectors are not the only use of quotes in CSS (e.g. content/font-family). As we should pick just one standard it would be equally odd to have double quoted strings for content values.

**Comment by jdforrester** [comment]
No movement in six weeks. Declining.

**Comment by Volker-E** [comment]
HTML and CSS are siblings and latter doesn't exist without former (XML). JS is independent from both and can be used in complete different contexts. Are we going to change HTML strings as well then?

**Comment by edg2s** [comment]
While I appreciate writing [attribute='value'] feels odd comparing it to HTML, this is not the only use case. For example in OOUI (and other places using lots of LESS) this represents a very small minority of quotes. The rest are LESS arguments, import paths or content strings, which have no equivalent in HTML.

**Comment by jdlrobson** [comment]
Just a general concern that I am worried about having two many meaningless CSS linting rules. The benefit of linting rules is they should help drive good code e.g. encourage developers not to use id selectors, to organise them by specificity. Linting should be sensible, help us write better code but things like this one seem unnecessary. I personally don't care if it's a single quote or a double quote.

This seems like a rule that falls into the bikeshed category (like the leading 0). Two different viewpoints, no real benefit.

**Comment by edg2s** [comment]
Linting also makes code easier to grep. Enforcing quotes and number styles helps with that - even if there's little to choose between which setting we go with.

**Comment by jdforrester** [comment]
Declining.
