### ISSUE TITLE
Address 8.0 deprecation warnings

### ISSUE THREAD

**Issue by edg2s** [wikimedia/stylelint-config-wikimedia#42]
From the VE build:

1. 'no-browser-hacks' has been deprecated and in 8.0 will be removed. See: https://stylelint.io/user-guide/rules/no-browser-hacks/
2. 'no-unsupported-browser-features' has been deprecated and in 8.0 will be removed. See: https://stylelint.io/user-guide/rules/no-unsupported-browser-features/
3. 'block-no-single-line' has been deprecated and in 8.0 will be removed. Instead use 'block-opening-brace-newline-after' and 'block-closing-brace-newline-before' with the "always" option. See: https://stylelint.io/user-guide/rules/block-no-single-line/
4. 'selector-root-no-composition' has been deprecated and in 8.0 will be removed. See: https://stylelint.io/user-guide/rules/selector-root-no-composition/
5. 'media-feature-no-missing-punctuation' has been deprecated and in 8.0 will be removed. See: https://stylelint.io/user-guide/rules/media-feature-no-missing-punctuation/
6. 'at-rule-empty-line-before's' "blockless-group" option has been deprecated and in 8.0 will be removed. Instead use the "blockless-after-blockless" option. See: https://stylelint.io/user-guide/rules/at-rule-empty-line-before/

**Comment by jdforrester** [comment]
Items 1 and 2 are configured locally.

Item 3 is fixed by #43.
Item 4 is fixed by #44.
Item 5 is fixed by #45.
Item 6 is fixed by #46.

Reviews welcome. Do we need to bump our peer version dependency in package.json (currently 7.3.1)?

**Comment by Volker-E** [comment]
`media-feature-no-missing-punctuation` seems like a missing block for our cause. I guess, we have to look into the https://github.com/csstree/csstree stylelint plugin instead…

**Comment by jdforrester** [comment]
First two dealt with in https://gerrit.wikimedia.org/r/#/c/338376/ so I'm declaring this completed.
