### ISSUE TITLE
Make rules follow a logical order in the definition

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#5]
Rules currently don't seem to follow a specific order, let's bring them in a logical order for better scan-ability, especially when you have to build project-own rules on top and have to compare it to own rules.

**Comment by jdforrester** [comment]
They were following the order given at http://stylelint.io/user-guide/rules/ but it's drifted a little.

**Comment by Volker-E** [comment]
Yeah, I thought that might be the reason. But with grown number of rules it's getting confusing. 
Please give the laid-out approach, alphabetical and sub-groups separated by a line when enclosing more than 3 rules a shot.

**Comment by Volker-E** [comment]
stylelint in their codebase themselves follow alphabetical order https://github.com/stylelint/stylelint/blob/master/src/rules/index.js
