### ISSUE TITLE
Inconsistency regarding id selectors

### ISSUE THREAD

**Issue by BenignBeppe** [wikimedia/stylelint-config-wikimedia#55]
`selector-no-id` is enabled, but https://www.mediawiki.org/wiki/Manual:Coding_conventions/CSS starts: 

> Name classes and IDs the same way [...]

While not explicitly allowing id selectors, this makes it sound like they're OK to use. Also, some of the examples use id selectors. Please update config or MW page to whichever is correct.

**Comment by edg2s** [comment]
We should update the documentation. IDs are not encouraged but there are lots of legacy IDs in the skins.

**Comment by edg2s** [comment]
Done in https://www.mediawiki.org/w/index.php?title=Manual%3ACoding_conventions%2FCSS&type=revision&diff=2414903&oldid=2407444
