### ISSUE TITLE
Remove `block-closing-brace-space-after` rule for now

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#6]
`block-closing-brace-space-after` runs into errors –no matter which config– on rules like
`.theme-oo-ui-outlineControlsWidget () {`

See https://gerrit.wikimedia.org/r/#/c/289599/
Let's remove it for now and revisit it.

**Comment by edg2s** [comment]
The OOUI library is fairly exceptional in doing this. The wikimedia preset can be overridden in the repo.

**Comment by Volker-E** [comment]
Mind my words: “no matter which config”. ;)

**Comment by edg2s** [comment]
You can set it to false to disable it.

**Comment by Volker-E** [comment]
That easy, alright. Wasn't clear from documentation.
