### ISSUE TITLE
Investigate indentation false positive in LESS file

### ISSUE THREAD

**Issue by umherirrender** [wikimedia/stylelint-config-wikimedia#62]
Have disable the indentation rule in https://gerrit.wikimedia.org/r/#/c/369874/5/view/resources/wikibase/wikibase.less

Running "stylelint:all" (stylelint) task
>> view/resources/wikibase/wikibase.less
>>  51:1  ✖  Expected indentation of 1 tab   indentation
Warning: Task "stylelint:all" failed. Use --force to continue

But line 51 is a selector and should have 0 tabs for indentation. The line before has a not, please have a look and may report upstream if there is a bug in stylelint itself.
The same as css file works correctly.

Thanks

**Comment by Volker-E** [comment]
This doesn't seem to be an issue any more, tested with stylelint v9.2.0 & stylelint-config-wikimedia v0.4.3:
https://gerrit.wikimedia.org/r/#/c/mediawiki/extensions/Wikibase/+/476402/
