### ISSUE TITLE
Updgrade to align to stylelint 8.2.0

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#65]
https://github.com/stylelint/stylelint/releases/tag/8.2.0

**Comment by jdforrester** [comment]
I've read through the changed rules list and there doesn't look to be anything new we'd want.

**Comment by Volker-E** [comment]
I agree after looking closely. While version 8.0.0 has only removed deprecated rules, none of 8.0.0, 8.1.0 or 8.2.0 have added a rule, only options.
We should consider adding `selector-max-specificity` at some point. But that's for another task.
