### ISSUE TITLE
'declaration-block-no-duplicate-properties' exception 'consecutive-duplicates' might do more harm than good

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#85]
Coming from https://gerrit.wikimedia.org/r/#/c/mediawiki/extensions/VipsScaler/+/483484/1/modules/ext.vipsScaler/ext.vipsScaler.css
it seems that ignoring 'consecutive-duplicates' as general rule seems to be overly loose rule. 
We should consider having devs go for `stylelint-disable-next-line` instead if they need it for progressively enhancing browser rendering quirks (example: color: rgb() over hex value.)

**Comment by Volker-E** [comment]
When enabling it without ignore exception on core, I receive 29 errors across files, but all tested are actually addressing browser quirks like vendor prefixed values etc. 
Closing again with that insight.

**Comment by Krinkle** [comment]
Hm.. it seems like this might be an upstream issue.

`-webkit-box-shadow` and `box-shadow` are not duplicative in the same way that writing `box-shadow` twice is. The latter should be made into a violation, even if we always want to allow the former. And, I'd hope that this is a fairly easy distinction to make within the stylelint code.

Re-opening so I won't forget to check with upstream. But feel free to re-close after a few weeks, if we don't want to keep it on backlogs indefinitely.

**Comment by Volker-E** [comment]
Seems to be a misunderstanding. I felt like, we should consider
```
box-shadow: …;
box-shadow: …;
```
to be flagged. Which is what the current rule ignoring browser quirks rules like
```
color: #000;
color: rgb( 0, 0, 0);
```
does not flag in general.

But looking through just the property duplications in core, it seems like we should stay with what we have and there are no false positives, but just browser quirkarounds. ;)

**Comment by Krinkle** [comment]
Closing for now. So long as different property names (e.g. vendor prefixes), or fallback values (modern vs old syntax) are considered "duplicate" by stylelint, we need to allow it.

The benefit of allowing them nearby is also that they presumably are much easier to catch in code review in case they really are redundant duplicates.
