### ISSUE TITLE
Prevent use of overly-generic class names without prefixes

### ISSUE THREAD

**Issue by edg2s** [wikimedia/stylelint-config-wikimedia#86]
As per https://www.mediawiki.org/wiki/Manual:Coding_conventions/CSS:

>  In MediaWiki core, use the `mw-` prefix. In extensions, use a `ext-myextensioncodename-` prefix

This means every class name should contain at least one hypen.

For stricter enforcement, we could also create a list of allowed prefixes, with `mw-` and `ext-` as the default.

**Comment by edg2s** [comment]
This rule would be as simple as:
`"selector-class-pattern": "-"`

A more advanced whitelist would look like:
`"selector-class-pattern": "(mw|ext-myextension)-"`

**Comment by edg2s** [comment]
Or we could apply a generic set:
`(mw|ext|oo-ui)-`

**Comment by edg2s** [comment]
`^(ext|mw|oo-ui|client|skin)-` is a better default.

**Comment by jdforrester** [comment]
If we're going to add `oo-ui` at the top level, let's add `cdx` too.

**Comment by edg2s** [comment]
The main problem with this rule is that if you want to "extend" it you have to copy and paste the upstream regex, so you then no longer get any upstream updates to it.

**Comment by jdforrester** [comment]
> The main problem with this rule is that if you want to "extend" it you have to copy and paste the upstream regex, so you then no longer get any upstream updates to it.

Yeah; worth asking upstream if this could be augmented with `selector-class-prefix-patterns`, which takes an array of prefixes which downstream could extend?

**Comment by edg2s** [comment]
Even if such a rule existed (or one could just re-use the existing rule, and add support for arrays) I don't think you can do array-merge extending?

**Comment by Volker-E** [comment]
How should we deal with classes like `sitedir`, `page`, `ns`?
