### ISSUE TITLE
Review new rules as of stylelint 10.0.0

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/stylelint-config-wikimedia#91]
From https://github.com/stylelint/stylelint/releases/tag/10.0.0:

* Added: `at-rule-property-requirelist` rule (#3997).
* Added: `disallowInList` to `no-duplicate-selectors` (#3936).
* Added: `ignore: ["comments"]` to `block-no-empty` (#4008).

**Comment by jdforrester** [comment]
CC @edg2s @Volker-E

**Comment by Volker-E** [comment]
* `at-rule-property-requirelist` 
Maybe in future, don't see a specific use-case right now.
* `disallowInList` 
Doesn't seem useful on a multi repo level.
* `ignore: ["comments"]`
I personally don't want multi-line spaces in comments…

**Comment by jdforrester** [comment]
WFM. Sounds like this is resolved. :-)
