### ISSUE TITLE
Add "unit-blacklist": "rem" to config

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#94]
In our environment, with skins providing independent font-size bases,`rem` is not a good choice and should be the explicit exception.
https://stylelint.io/user-guide/rules/unit-blacklist/#unit-blacklist

Ha, https://codesearch.wmflabs.org/deployed/?q=rem%3B&i=nope&files=&repos=

**Comment by jdforrester** [comment]
Seems sensible.

**Comment by j4n-co** [comment]
Shouldn't this stylelint config be useable by skins as well? If a skin chooses to use rems, I think this stylelint config should still be compatible with it.

**Comment by edg2s** [comment]
That can be a per project exception if someone is already using them, but I think it's ok for us to be opinionated about this for new code.

**Comment by j4n-co** [comment]
Alright, so from my understanding the main reason we want to avoid using rems is: 
1. browser support
2. Mitigating the [62.5% hack](https://snook.ca/archives/html_and_css/font-size-with-rem), which, I guess is a thing [people](https://stackoverflow.com/questions/40372752/whats-the-correct-way-to-set-a-base-rem-value-in-css) [do](https://stackoverflow.com/questions/47923397/css-fonts-rem-trick-62-5-or-6-25), so I don't discount that.

**Comment by Volker-E** [comment]
No, those are only two minor issues. I proposed it as I think that folks with less CSS experience apply `rem`s wrong. They've probably read that it's better than `em`s without having the pros and cons in front of them.

The proposal here targets at things like
https://gerrit.wikimedia.org/g/mediawiki/extensions/WikibaseMediaInfo/+/499311d60a0172e5f8bf6280b745e546477e9772/resources/filepage/styles/mediainfo-filepage-mixins.less#40
which makes little to no sense.
